import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("macOS shell reads the shared WebView host config", async () => {
  const source = await readFile("apps/native-shells/macos/Sources/KeelMacShell/main.swift", "utf8");
  const manifest = await readFile("apps/native-shells/macos/Package.swift", "utf8");

  assert.match(manifest, /executable\(name: "KeelMacShell"/);
  assert.match(source, /import WebKit/);
  assert.match(source, /desktop-host\/webview\.config\.json/);
  assert.match(source, /WKWebView/);
  assert.match(source, /WKScriptMessageHandler/);
  assert.match(source, /name: "keelHost"/);
  assert.match(source, /clipboard\.writeText/);
  assert.match(source, /globalHotkey\.register/);
  assert.match(source, /toast\.show/);
  assert.match(source, /toast\.hide/);
  assert.match(source, /popover\.show/);
  assert.match(source, /tooltip\.show/);
  assert.match(source, /prewarmBeforeShow/);
  assert.match(source, /windowShouldClose/);
  assert.match(source, /hideWindow/);
  assert.match(source, /hideTransientSurfaces/);
  assert.match(source, /hideAll/);
  assert.match(source, /isEscape/);
  assert.match(source, /normalizedAcceleratorKey/);
  assert.match(source, /case "space": return " "/);
  assert.match(source, /popoverMaxSize = NSSize\(width: 320, height: 180\)/);
  assert.match(source, /tooltipMaxSize = NSSize\(width: 240, height: 72\)/);
  assert.match(source, /toastMaxSize = NSSize\(width: 320, height: 140\)/);
  assert.match(source, /toastScreenVerticalRatio: CGFloat = 0\.24/);
  assert.match(source, /screenFrame\.midX/);
  assert.match(source, /showToast/);
  assert.match(source, /panel\.hasShadow = false/);
  assert.match(source, /panelLayout/);
  assert.match(source, /multilineHeight/);
  assert.match(source, /cornerRadius: CGFloat = 10/);
  assert.match(source, /material = \.popover/);
  assert.match(source, /config\.frontend\.devUrl/);
});

test("Windows shell reads the shared WebView host config", async () => {
  const project = await readFile("apps/native-shells/windows/Keel.WindowsShell.csproj", "utf8");
  const xaml = await readFile("apps/native-shells/windows/MainWindow.xaml", "utf8");
  const source = await readFile("apps/native-shells/windows/MainWindow.xaml.cs", "utf8");

  assert.match(project, /Microsoft\.Web\.WebView2/);
  assert.match(project, /net9\.0-windows/);
  assert.match(xaml, /WebView2/);
  assert.match(source, /desktop-host\/webview\.config\.json/);
  assert.match(source, /WebMessageReceived/);
  assert.match(source, /AdditionalBrowserArguments/);
  assert.match(source, /clipboard\.writeText/);
  assert.match(source, /RegisterHotKey/);
  assert.match(source, /globalHotkey\.register/);
  assert.match(source, /toast\.show/);
  assert.match(source, /toast\.hide/);
  assert.match(source, /popover\.show/);
  assert.match(source, /tooltip\.show/);
  assert.match(source, /PrewarmBeforeShow/);
  assert.match(source, /HideNativeOverlays/);
  assert.match(source, /PreviewKeyDown/);
  assert.match(source, /Key\.Escape/);
  assert.match(source, /_hotkeyIdsByLogicalId/);
  assert.match(source, /PopoverMaxWidth = 320/);
  assert.match(source, /TooltipMaxWidth = 240/);
  assert.match(source, /ToastMaxWidth = 320/);
  assert.match(source, /ToastScreenVerticalRatio = 0\.72/);
  assert.match(source, /PlacementMode\.AbsolutePoint/);
  assert.match(source, /SystemParameters\.WorkArea/);
  assert.match(source, /ShowToast/);
  assert.match(source, /MinWidth = minWidth/);
  assert.match(source, /MaxWidth = maxWidth/);
  assert.match(source, /OverlayCornerRadius = 10/);
  assert.match(source, /BorderThickness = new Thickness\(0\)/);
  assert.match(source, /BlurRadius = 24/);
  assert.match(source, /CoreWebView2\.Navigate/);
});
