// Generated by tools/generate-protocol.mjs. Do not edit by hand.

use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: &str = "0.1.0";

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ExtensionInfo {
    pub id: String,
    pub name: String,
    pub version: String,
    pub capabilities: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct InitializeParams {
    #[serde(rename = "hostVersion")]
    pub host_version: String,
    pub extension: ExtensionInfo,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct InitializeResult {
    pub ready: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SearchQueryParams {
    pub query: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<f64>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SearchItem {
    pub id: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtitle: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub score: Option<f64>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SearchQueryResult {
    pub items: Vec<SearchItem>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CommandRunParams {
    #[serde(rename = "commandId")]
    pub command_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<serde_json::Value>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CommandRunResult {
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct RpcError {
    pub code: String,
    pub message: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "method", content = "params")]
pub enum RpcRequestParams {
    #[serde(rename = "extension.initialize")]
    ExtensionInitialize(InitializeParams),
    #[serde(rename = "search.query")]
    SearchQuery(SearchQueryParams),
    #[serde(rename = "command.run")]
    CommandRun(CommandRunParams),
}

pub const EXTENSION_INITIALIZE: &str = "extension.initialize";
pub const SEARCH_QUERY: &str = "search.query";
pub const COMMAND_RUN: &str = "command.run";

