// Generated by tools/generate-protocol.mjs. Do not edit by hand.

export const protocolVersion = "0.1.0" as const;

export interface ExtensionInfo {
  id: string;
  name: string;
  version: string;
  capabilities: string[];
}

export interface InitializeParams {
  hostVersion: string;
  extension: ExtensionInfo;
}

export interface InitializeResult {
  ready: boolean;
  message?: string;
}

export interface SearchQueryParams {
  query: string;
  limit?: number;
}

export interface Action {
  id: string;
  title: string;
  style?: string;
  shortcut?: string;
}

export interface ActionPanel {
  actions: Action[];
}

export interface Toast {
  title: string;
  message?: string;
  style?: string;
}

export interface SearchItem {
  id: string;
  title: string;
  subtitle?: string;
  score?: number;
  actions?: Action[];
}

export interface SearchQueryResult {
  items: SearchItem[];
}

export interface CommandRunParams {
  commandId: string;
  arguments?: unknown;
}

export interface CommandRunResult {
  ok: boolean;
  message?: string;
  toast?: Toast;
  actions?: Action[];
}

export interface NativeBridgeParams {
  method: string;
  params?: unknown;
}

export interface NativeBridgeResult {
  ok: boolean;
  value?: unknown;
}

export interface RpcError {
  code: string;
  message: string;
}

export interface MethodMap {
  "extension.initialize": { params: InitializeParams; result: InitializeResult };
  "search.query": { params: SearchQueryParams; result: SearchQueryResult };
  "command.run": { params: CommandRunParams; result: CommandRunResult };
  "host.invoke": { params: NativeBridgeParams; result: NativeBridgeResult };
}

export type MethodName = keyof MethodMap;
export type RpcRequest<M extends MethodName = MethodName> = {
  id: string;
  method: M;
  params: MethodMap[M]["params"];
};
export type RpcResponse<M extends MethodName = MethodName> = {
  id: string;
  result?: MethodMap[M]["result"];
  error?: RpcError;
};

export const methods = {
  EXTENSION_INITIALIZE: "extension.initialize",
  SEARCH_QUERY: "search.query",
  COMMAND_RUN: "command.run",
  HOST_INVOKE: "host.invoke",
} as const;

